apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4=
  mongo-password: cGFzc3dvcmQ=
  mongo-url: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvLXNlcnZpY2U6MjcwMTcvP2F1dGhTb3VyY2U9YWRtaW4=
  mongo-user-account: dXNlci1hY2NvdW50